### ISSUE TITLE
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer

### ISSUE THREAD

**Issue by ktmswzw** [louislivi/fastdep#3]
FastDepRedisRegister
:(Integer)map.get("port")

yml:
comm: #连接名称
      database: 2
      host: ${app.server.redis.host}
      password: ${app.server.redis.password}
      port: ${app.server.redis.port}

dev.yml

redis:
      host: 127.0.01
      port: 43379
      password: 123qwe$R0,0.

**Comment by louislivi** [comment]
示例
```yml
  redis:
    redis1:
      database: 0
      host: 127.0.0.1
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
    redis2:
      database: 1
      host: 127.0.0.1
      port: 6379
      lettuce: #下面为连接池的补充设置
        shutdown-timeout: 100 # 关闭超时时间
        pool:
          max-active: 18 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          max-wait: 30 # 连接池最大阻塞等待时间（使用负值表示没有限制）
          min-idle: 0 # 连接池中的最小空闲连接
```
层级必须为
```yml
redis:
    连接名称:
      database: 0
      host: 192.168.12.88
      port: 6379
      ...
```
